"""Add idempotency_key to tickets table

Revision ID: fbea495c14b0
Revises: 3470d9565509
Create Date: 2026-10-03 15:02:47.471740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbea495c14b0'
down_revision: Union[str, Sequence[str], None] = '3470d9565509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.create_index(
        "ix_tickets_idempotency_key",
        "tickets",
        ["idempotency_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tickets_idempotency_key", table_name="tickets")
    op.drop_column('tickets', 'idempotency_key')
    # ### end Alembic commands ###
