from datetime import date
from typing import Protocol
from uuid import UUID

from app.domain.entities import Event, OutboxRecord, Place, SyncState, Ticket


class TicketRepository(Protocol):
    async def create(self, ticket: Ticket) -> None: ...

    async def get(self, ticket_id: UUID) -> Ticket | None: ...

    async def get_by_idempotency_key(self, idempotency_key: str) -> Ticket | None: ...

    async def delete_by_id(self, ticket_id: UUID) -> bool: ...


class EventRepository(Protocol):
    async def get_by_id(self, event_id: UUID) -> Event | None: ...

    async def upsert(self, event: Event) -> None: ...

    async def get_list_paginated(
        self, date_from: date | None = None, page: int = 1, page_size: int = 20
    ) -> list[Event]: ...

    async def count(self, date_from: date | None = None) -> int: ...


class PlaceRepository(Protocol):
    async def upsert(self, place: Place) -> None: ...


class SyncRepository(Protocol):
    async def get_state(self) -> SyncState: ...

    async def save_state(self, state: SyncState) -> None: ...


class OutboxRepository(Protocol):
    async def create(self, record: OutboxRecord) -> None: ...

    async def get_pending(self, limit: int) -> list[OutboxRecord]: ...

    async def mark_sent(self, record_id: UUID) -> None: ...

    async def mark_failed_attempt(self, record_id: UUID) -> None: ...

    async def mark_failed(self, record_id: UUID) -> None: ...
